swiftmailer:
    transport: smtp.gmail.com
    username:  null
    password:  null
    host: localhost
    port: 465
    encryption: ssl
    auth-mode: login
    disable_delivery: true
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false
