vich_uploader:
    db_driver: orm

    mappings:
         blog_images:
             uri_prefix: /images/blog
             upload_destination: '%kernel.project_dir%/public/images/blog'
             namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
